os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake libcurl3 libarchive-dev
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install libstdc++-4.9-dev llvm-3.5 llvm-3.5-dev clang-3.5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [ "$CXX" = "clang++" ]; then $CXX --version; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install: ./bootstrap.sh

script: ./build.sh && ./test.sh

